eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
