server:
  port: 8090

spring:
  application:
    name: review-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewdb
    username: postgres
    password: postgres
  elasticsearch:
    uris: http://localhost:9200
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
